In [1]:
from kosac.lexicon import PolarityLexicon as Lexicon
from kosac.corpora import Corpus
from kosac.tokenizers import KomoranTokenizer

In [2]:
lexicon = Lexicon('./lexicon/polarity.csv')

lexicon.set_lexicon(min_freq=5)
lexicon.get_size()

373

In [8]:
print(lexicon)

PolarityLexicon(ngrams=[1], min_freq=5, threshold=0.0)

In [6]:
lexicon.get_lexicon()

        ngram  freq  COMP  NEG  NEUT  None  POS max.value  max.prop
entry
ㄴ/ETM       1   289     6  107    17    22  137       POS  0.474048
ㄴ/JX        1    22     3    9     1     2    7       NEG  0.409091
ㄴ가/EC       1     6     1    2     0     3    0      None  0.500000
ㄴ가/EF       1     9     1    3     0     5    0      None  0.555556
ㄴ다/EC       1     5     0    0     3     1    1      NEUT  0.600000
...       ...   ...   ...  ...   ...   ...  ...       ...       ...
확인/NNG      1     5     0    4     0     0    1       NEG  0.800000
훨씬/MAG      1     9     0    3     0     0    6       POS  0.666667
흐르/VV       1     5     0    4     0     0    1       NEG  0.800000
흥행/NNG      1     6     0    0     0     0    6       POS  1.000000
힘/NNG       1     7     0    1     0     0    6       POS  0.857143

[373 rows x 9 columns]

In [4]:
lexicon.get_entry('힘/NNG')

ngram               1
freq                7
COMP                0
NEG                 1
NEUT                0
None                0
POS                 6
max.value         POS
max.prop     0.857143
Name: 힘/NNG, dtype: object

In [5]:
corpus = Corpus('./data/example.csv')
corpus.df

      text label
0  나는 기뻐요.   POS
1  나는 슬퍼요.   NEG