In [1]:
from kosac.tokenizers import KomoranTokenizer, HuggingTokenizer

In [2]:
sentence = '잠이 옵니다.'

In [3]:
tokenizer1 = KomoranTokenizer(userdic='./tagger/user_dictionary.txt')
tokenizer1.tokenize(sentence)

['자/VV', 'ㅁ/ETN', '이/JKS', '오/VV', 'ㅂ니다/EF', './SF']

In [4]:
tokenizer2 = HuggingTokenizer()
tokenizer2.tokenize(sentence)
tokenizer2.tagger_type

transformers.models.electra.tokenization_electra_fast.ElectraTokenizerFast

In [5]:
tokenizer3 = HuggingTokenizer(model_name='snunlp/KR-Medium')
tokenizer3.tokenize(sentence)
tokenizer3.tagger_type

transformers.models.bert.tokenization_bert_fast.BertTokenizerFast

In [6]:
from kosac.lexicon import PolarityLexicon, IntensityLexicon, SubjectivityTypeLexicon

In [7]:
lexicon1 = PolarityLexicon(filepath='./lexicon/polarity.csv')
lexicon1.get_lexicon()

                   ngram  freq  COMP  NEG  NEUT  None  POS max.value  max.prop
entry
ㄴ/ETM                  1   289     6  107    16    21  137       POS  0.474048
ㄴ/ETM 가슴/NNG           2     1     0    0     0     0    1       POS  1.000000
ㄴ/ETM 가슴/NNG 은/JX      3     1     0    0     0     0    1       POS  1.000000
ㄴ/ETM 감/NNG            2     1     0    1     0     0    0       NEG  1.000000
ㄴ/ETM 감/NNG 이/JKS      3     1     0    1     0     0    0       NEG  1.000000
...                  ...   ...   ...  ...   ...   ...  ...       ...       ...
힘들/VA 고/EC             2     1     0    0     0     0    1       POS  1.000000
힘들/VA 고/EC 외롭/VA       3     1     0    0     0     0    1       POS  1.000000
힘차/VA                  1     1     0    1     0     0    0       NEG  1.000000
힘차/VA ㄴ/ETM            2     1     0    1     0     0    0       NEG  1.000000
힘차/VA ㄴ/ETM 붓/NNG      3     1     0    1     0     0    0       NEG  1.000000

[16362 rows x 9 columns]

In [8]:
lexicon1.get_entry('힘들/VA')

ngram           1
freq            4
COMP            0
NEG             3
NEUT            0
None            0
POS             1
max.value     NEG
max.prop     0.75
Name: 힘들/VA, dtype: object

In [9]:
lexicon2 = IntensityLexicon(filepath='./lexicon/intensity.csv', ngrams=[1])
lexicon2.set_lexicon(min_freq=20)
lexicon2.get_lexicon()

       ngram  freq  High  Low  Medium  None max.value  max.prop
entry
ㄴ/ETM      1   289    40   27     197    21    Medium  0.685121
ㄴ/JX       1    22     2    0      17     2    Medium  0.772727
ㄹ/ETM      1   187    18   15      75    75    Medium  0.406417
ㅁ/ETN      1    22     0    2      17     0    Medium  0.772727
가/JKS      1   112    18   11      77     4    Medium  0.696429
...      ...   ...   ...  ...     ...   ...       ...       ...
하/VV       1    87    10   11      48    18    Medium  0.551724
하/VX       1   144     9    4      42    89      None  0.618056
하/XSA      1   333    37   27     258     8    Medium  0.774775
하/XSV      1   465    64   53     332    14    Medium  0.713978
화/XSN      1    25     3    3      19     0    Medium  0.760000

[86 rows x 8 columns]

In [10]:
lexicon3 = SubjectivityTypeLexicon(filepath='./lexicon/subjectivity-type.csv', ngrams=[1])
lexicon3.set_lexicon(min_freq=5)
lexicon3.get_lexicon()

,ngram,freq,Agreement,Argument,Emotion,Intention,Judgment,Others,Speculation,max.value,max.prop
entry,,,,,,,,,,,
ㄴ/ETM,1,289,1,96,11,1,155,17,4,Judgment,0.536332
ㄴ/JX,1,22,0,13,0,0,2,2,2,Argument,0.636364
ㄴ가/EC,1,6,0,1,0,0,1,1,1,Judgment,0.333333
ㄴ가/EF,1,9,0,1,0,0,2,2,0,Judgment,0.333333
ㄴ다/EC,1,5,0,3,0,1,0,1,0,Argument,0.600000
...,...,...,...,...,...,...,...,...,...,...,...
확인/NNG,1,5,0,4,0,0,1,0,0,Argument,0.800000
훨씬/MAG,1,9,0,0,0,0,9,0,0,Judgment,1.000000
흐르/VV,1,5,0,4,0,0,1,0,0,Argument,0.800000
흥행/NNG,1,6,0,0,0,0,6,0,0,Judgment,1.000000
힘/NNG,1,7,0,1,0,0,5,0,0,Judgment,0.857143

In [11]:
lexicon3.get_smoothed_lexicon()

,Agreement,Argument,Emotion,Intention,Judgment,Others,Speculation
entry,,,,,,,
ㄴ/ETM,0.006849,0.332192,0.041096,0.006849,0.534247,0.061644,0.017123
ㄴ/JX,0.038462,0.538462,0.038462,0.038462,0.115385,0.115385,0.115385
ㄴ가/EC,0.090909,0.181818,0.090909,0.090909,0.181818,0.181818,0.181818
ㄴ가/EF,0.083333,0.166667,0.083333,0.083333,0.250000,0.250000,0.083333
ㄴ다/EC,0.083333,0.333333,0.083333,0.166667,0.083333,0.166667,0.083333
...,...,...,...,...,...,...,...
확인/NNG,0.083333,0.416667,0.083333,0.083333,0.166667,0.083333,0.083333
훨씬/MAG,0.062500,0.062500,0.062500,0.062500,0.625000,0.062500,0.062500
흐르/VV,0.083333,0.416667,0.083333,0.083333,0.166667,0.083333,0.083333
흥행/NNG,0.076923,0.076923,0.076923,0.076923,0.538462,0.076923,0.076923
힘/NNG,0.076923,0.153846,0.076923,0.076923,0.461538,0.076923,0.076923