# KOSAC Lexicon for Social Scientists

2024-01-25 Sumin

## 데모

In [21]:
from utils import *

In [22]:
kosac = SentLex(filepath='lexicon/polarity.csv', ngrams=[1])
kosac.set_lexicon(min_freq=5)
kosac.get_lexicon()

        ngram  freq  COMP  NEG  NEUT  None  POS max.value  max.prop
entry
ㄴ/ETM       1   289     6  107    16    21  137       POS  0.474048
ㄴ/JX        1    22     2    8     0     2    6       NEG  0.409091
ㄴ가/EC       1     6     1    1     0     3    0      None  0.500000
ㄴ가/EF       1     9     0    2     0     5    0      None  0.555556
ㄴ다/EC       1     5     0    0     3     1    1      NEUT  0.600000
...       ...   ...   ...  ...   ...   ...  ...       ...       ...
확인/NNG      1     5     0    4     0     0    1       NEG  0.800000
훨씬/MAG      1     9     0    2     0     0    6       POS  0.666667
흐르/VV       1     5     0    4     0     0    1       NEG  0.800000
흥행/NNG      1     6     0    0     0     0    6       POS  1.000000
힘/NNG       1     7     0    1     0     0    5       POS  0.857143

[373 rows x 9 columns]

In [23]:
corpus = Corpus()
corpus.df

      text label
0  나는 기뻐요.   POS
1  나는 슬퍼요.   NEG

In [24]:
# tokenizer = Tokenizer(tagger_type='Transformer')
tokenizer = Tokenizer(tagger_type='Kkma')
print(tokenizer.tokenize('나는 슬퍼요.'))
print(tokenizer.get_ngrams('나는 슬퍼요.', [1,2]))

['나/NP', '는/JX', '슬프/VA', '어요/EFN', './SF']
['나/NP', '는/JX', '슬프/VA', '어요/EFN', './SF', '나/NP 는/JX', '는/JX 슬프/VA', '슬프/VA 어요/EFN', '어요/EFN ./SF']

### `SentLex` 클래스: (일반화 가능한) 감정사전

In [25]:
sentlex = SentLex(ngrams=[1,2])
sentlex.get_lexicon()

Empty DataFrame
Columns: []
Index: []

In [26]:
sentlex.update_from_corpus(corpus, tokenizer)
sentlex.get_lexicon()

             ngram freq COMP NEG NEUT None POS max.value  max.prop
entry
나/NP             1    2    0   1    0    0   1       NEG       0.5
는/JX             1    2    0   1    0    0   1       NEG       0.5
기쁘/VA            1    1    0   0    0    0   1       POS       1.0
어요/EFN           1    2    0   1    0    0   1       NEG       0.5
./SF             1    2    0   1    0    0   1       NEG       0.5
나/NP 는/JX        2    2    0   1    0    0   1       NEG       0.5
는/JX 기쁘/VA       2    1    0   0    0    0   1       POS       1.0
기쁘/VA 어요/EFN     2    1    0   0    0    0   1       POS       1.0
어요/EFN ./SF      2    2    0   1    0    0   1       NEG       0.5
슬프/VA            1    1    0   1    0    0   0       NEG       1.0
는/JX 슬프/VA       2    1    0   1    0    0   0       NEG       1.0
슬프/VA 어요/EFN     2    1    0   1    0    0   0       NEG       1.0