In [1]:
from utils import *

In [2]:
# raw polarity lexicon
lexicon = get_lexicon(min_freq=5)
lexicon

                  ngram  freq  COMP  NEG  NEUT  None  POS max.value  max.prop
entry
하/VV 지/EC 않/VX        3     5     0    5     0     0    0       NEG  1.000000
하/XSA 지/EC 않/VX       3     7     0    7     0     0    0       NEG  1.000000
을/ETM 수/NNB 없/VA      3     9     0    3     0     0    5       POS  0.555556
하/XSV 아/EC 주/VX       3     7     0    3     0     1    2       NEG  0.571429
ㄹ/ETM 수/NNB 없/VA      3    21     1   11     1     3    1       NEG  0.571429
...                 ...   ...   ...  ...   ...   ...  ...       ...       ...
화려/XR                 1     6     0    0     0     0    6       POS  1.000000
본격/NNG                1     5     0    0     0     0    5       POS  1.000000
보복/NNG                1     6     0    6     0     0    0       NEG  1.000000
충격/NNG                1     5     0    5     0     0    0       NEG  1.000000
상/NNG                 1     5     0    0     0     0    5       POS  1.000000

[613 rows x 9 columns]

In [3]:
# Add unigram entries into user dictionary for tagger
update_dict(lexicon)

USERDIC: ./tagger/user_dictionary.txt

In [4]:
# Use Komoran Tagger
tagger = get_tagger()

In [5]:
# morpheme tokenizer
sentence = '모든 인간은 태어날 때부터 자유로우며 그 존엄과 권리에 있어 동등하다.'
tokenize(sentence, tagger)

'모든/MM 인간/NNG 은/JX 태어나/VV ㄹ/ETM 때/NNG 부터/JX 자유/NNG 롭/XSA 며/EC 그/MM 존엄/NNG 과/JKB 권리/NNG 에/JKB 있/VV 어/EC 동등/NNG 하/XSV 다/EF ./SF'

In [6]:
# find sentiment lexicon items
get_match_info(sentence, tagger, lexicon)

[('모든/MM', 'POS', 0.6),
 ('인간/NNG', 'NEG', 0.6),
 ('은/JX', 'NEG', 0.559322034),
 ('나/VV', 'POS', 0.714285714),
 ('ㄹ/ETM 때/NNG', 'NEUT', 0.428571429),
 ('부터/JX', 'POS', 0.625),
 ('자유/NNG 롭/XSA', 'POS', 0.6),
 ('며/EC', 'NEG', 0.444444444),
 ('그/MM', 'POS', 0.538461538),
 ('과/JKB', 'POS', 0.636363636),
 ('에/JKB', 'POS', 0.378205128),
 ('있/VV', 'None', 0.455357143),
 ('어/EC', 'POS', 0.495867769),
 ('하/XSV', 'POS', 0.516129032),
 ('다/EF', 'NEG', 0.435483871)]

In [7]:
# Laplace smoothing
smooth(lexicon, add_one)

                      COMP       NEG      NEUT      None       POS
entry
하/VV 지/EC 않/VX    0.100000  0.600000  0.100000  0.100000  0.100000
하/XSA 지/EC 않/VX   0.083333  0.666667  0.083333  0.083333  0.083333
을/ETM 수/NNB 없/VA  0.076923  0.307692  0.076923  0.076923  0.461538
하/XSV 아/EC 주/VX   0.090909  0.363636  0.090909  0.181818  0.272727
ㄹ/ETM 수/NNB 없/VA  0.090909  0.545455  0.090909  0.181818  0.090909
...                    ...       ...       ...       ...       ...
화려/XR             0.090909  0.090909  0.090909  0.090909  0.636364
본격/NNG            0.100000  0.100000  0.100000  0.100000  0.600000
보복/NNG            0.090909  0.636364  0.090909  0.090909  0.090909
충격/NNG            0.100000  0.600000  0.100000  0.100000  0.100000
상/NNG             0.100000  0.100000  0.100000  0.100000  0.600000

[613 rows x 5 columns]

In [8]:
get_sent_probs(sentence, tagger, lexicon)

COMP    5.718111e-14
NEG     6.139923e-02
NEUT    6.175560e-10
None    9.354372e-11
POS     9.386008e-01
dtype: float64

In [9]:
get_sent_probs('학교종이 땡땡땡 어서 모이자', tagger, lexicon)

COMP    0.125
NEG     0.250
NEUT    0.125
None    0.250
POS     0.250
dtype: float64

In [13]:
get_sent_probs('빗물이 흐르고 내 눈물도 흐르고 잃어버린 첫사랑도 흐르네', tagger, lexicon)

COMP    2.834921e-13
NEG     9.969223e-01
NEUT    3.490598e-10
None    1.321036e-08
POS     3.077715e-03
dtype: float64